(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"index_atlas_1", frames: [[0,0,1262,325]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.terra_bg_970 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.tx2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AECDQIgIgDIgHgFQgCgDgCgFIgCgJIgBgcIgPAAIAAA1IgRAAIAAh7IARAAIAAA1IAPAAIABgcIACgJIAEgIIAHgFIAIgEIAJAAIAIAAIAJAEIAHAFIAEAIIADAJIAABJQAAAEgDAEIgEAIIgHAFQgEADgFABIgIABgAEEBlQgDACgBACIgCAHIgBAHIAAA4IABAHIACAGQACADACABQAEACADAAIAGgCQADgBACgDIACgGIABgHIAAg4IgBgHIgCgHQgCgCgDgCIgGgBQgDgBgEACgAmIDQIgMgDIgJgGQgEgDgDgGIgGgKQgBgFAAgHQAAgFACgJIAIgOIAJgLIAMgKIgLgJQgEgDgFgIQgDgGgDgHQgCgGAAgHQAAgGACgFIAEgKIAHgIQADgEAFgCIALgDIAKgCIALACIAKADQAFACAEAEIAHAIIADAKIACALQAAAHgCAGQgCAHgEAGQgEAHgEAEIgMAJIANAKIAJALQAEAFADAJQADAIAAAGQAAAIgCAEQgCAGgDAEQgDAGgFADQgEAEgGACIgKADIgKABgAmHCJIgIAIQgEAEgDAHQgDAGABAGQAAAGABAFQAEAFADACIAJAFIAKACQAFAAAFgCIAJgFQAEgDACgEQACgFAAgGQAAgGgCgGIgHgLIgIgIIgKgIIgKAIgAmGAzQgFACgDADIgFAHIgCAKQAAAFADAFIAFAKQADAEAFAEIAIAIIAJgIIAHgIIAGgKQACgFAAgFIgCgKQgCgFgDgCQgDgDgEgCQgFgBgFgBIgJACgAGJDPIAAg2IgzAAIAAA2IgSAAIAAh6IASAAIAAAzIAzAAIAAgzIASAAIAAB6gACfDPIADhkIgwBkIgXAAIAAh6IATAAIgDBkIAxhkIAWAAIAAB6gAg0DPIAAiYIghAZIgKgLIArgiIATAAIAACsgAnhDPIAAiYIgiAZIgKgLIAsgiIASAAIAACsgAH7DPIAAgvIgWAAIgfAvIgUAAIAfgwQgHgBgEgDIgKgJQgEgFgCgFQgBgHAAgHIABgKIADgKQACgEAEgEIAIgFQAFgCAFgBIAKgCIAzAAIAAB7gAHSBnQgEACgCAEIgEAHIgBAHIABAJQABAEADADQADADADACIAJABIAhAAIAAgrIghAAgAjPDPIAAgNIACgMIADgNIAFgMIAGgLIAJgJIAJgIIALgIIAKgIQAGgFACgEQAEgFACgGQABgGAAgGIgBgMIgFgKQgDgDgGgDQgEgDgHAAQgGAAgFACQgEABgEAEQgDADgBAGIgCAKIAAABIgTAAIAAgCIABgLIAFgLQACgFAFgEQADgEAGgDIALgEIALgBIANABQAHACAEADQAFACAFAGQAFAGACAEQADAGAAAFIABANQAAAHgBAGQgCAGgDAGQgCAFgGAHIgJAKQgDACgJAGIgKAJQgFAEgEAGQgFAFgDAFIgEANIgDANIBEAAIAAARgAlACIIAAgRIBlAAIAAARgAGighQgFgBgFgCQgGgDgEgEQgEgFgCgEIgFgLQgBgFAAgHIASAAIADAKQAAAFAFAEQAEAEAEACIALABIAJgBQAEgCAEgDIAFgHIADgJIABgJIAAgSIgBgJIgDgJIgFgHIgIgGIgIgCIgJABQgEABgEAEQgCABgDAFIgDAIIgSAAIAAheIBRAAIAAAQIg/AAIAAAxQAFgEAHAAIAMgBQAHAAAHACQAGABAGAEQAEAEAFAGQAEAGACAHQADAGAAAHIABAOIgBANIgDAOQgDAHgEAFQgEAGgFAEQgFAEgHACIgOABgADBghIgNgFQgFgDgEgEQgEgFgDgGQgDgHgBgGIgBgMIAAhOIABgNIAEgMQADgGAEgFQAFgFAEgDQAGgDAHAAIALgCQAHAAAGACIAMADQAGAEAEAEQADAEADAHQADAHABAFIAAANIAABPIAAAMQgBAFgDAHIgGALQgGAGgEACQgGADgGABIgNABIgLgBgACyhZIAAAQIACAHIAFAIIAFAGIAHACQACABAFAAIAJgBIAHgCIAFgGIAFgIIABgHIABg7gADEi/QgEABgEADIgFAFIgEAHIgCAIIgBA7IABAAIA2grIAAgQIgCgIIgEgHIgFgFQgFgDgDgBIgIgBgAkFghQgGgBgEgCQgFgDgFgEQgDgDgEgGIgDgLQgCgGAAgGIAAgCIASAAIAAABIACALQABAFAEAEQAEAEAEACIAMABQAEABAHgDQAFgCAEgFQAEgEAAgGQACgFAAgGIAAghIgpAAIAAgRIApAAIAAgfIgCgNQgBgFgDgFQgEgEgGgCQgFgDgGAAIgLABQgEADgFADQgCAEgDAFQgCAFAAAGIAAABIgRAAIAAgBIABgMIAEgKQACgFAFgFQAGgFADgCIALgDIAMgBIAMABQAJACADACQAEADAFAFQAGAFABAFQADAHABAEIABANIAABRIgBAMQgBAFgDAHQgBAEgGAGQgEAFgFADQgGADgGABQgGACgFAAgAESghIABgaIAEgMIAMgXIAIgKIAKgIIAUgQQAGgEACgFQAEgEABgHQACgGAAgGIgCgLQgBgGgDgFQgDgEgGgCQgGgDgFAAQgFABgFACQgFAAgEAFQgDADgCAFIgCALIAAABIgSAAIAAgCIABgMIAEgKQADgFAEgEQAFgFAEgCIALgDIAMgBIAMABIAMADQAEADAFAFQAEAFADAFIAEAMIABANQAAAGgBAHIgGANQgCAEgFAHIgKAJIgVASIgJAJIgHALIgGANIgCANIBEAAIAAARgAAwghIABgaQAAgHADgFIALgXIAJgKIAJgIIAVgQQAHgFACgEQADgFABgGIACgMIgCgLQgBgGgDgFQgCgDgHgDQgGgDgFAAQgEABgHACQgEAAgEAFQgDAEgCAEIgBALIAAABIgTAAIAAgCIACgMIADgKQADgFAFgEQADgEAGgDIAKgDIANgBIAMABQAHABAEACQAFADAEAFQAGAGABAEQADAIABAEIABANQAAAGgCAHQgBAGgDAHIgIALIgJAJIgVASIgKAJIgHALIgGANIgCANIBEAAIAAARgAiPghIAAgUIgDAAIgLgBQgGgCgEgEQgEgCgEgGIgFgKIgCgLIAAg9IACgLIAFgKQAEgGAEgCQAFgEAFgCQAGgBAFAAIADAAIAAgTIASAAIAAATIADAAIALABQAHACADAEQAFADADAFIAFAKIADALIAAA9QgBAIgCADQgBAFgEAFQgEAGgEACQgDAEgHACIgLABIgDAAIAAAUgAiZiqIgFAEIgEAHIgCAGIgBAHIAAA0IABAHIACAIIAEAFIAFAFQAEABADAAIAEAAIAAhnIgEAAQgDAAgEABgAh9hFIADAAQADAAADgBIAGgFIADgFIAEgHIABgIIAAg0IgBgHIgHgNQgCgDgEgBQgDgCgDAAIgDAAgAlOghIACiPIgXBaIgQAAIgXhaIACCPIgSAAIAAisIAWAAIAZBbIAYhbIAWAAIAACsgAnGghIAAicIgzAAIAACcIgSAAIAAisIBXAAIAACsgAhChpIAAgRIBlAAIAAARg");
	this.shape.setTransform(52.55,20.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.tx2, new cjs.Rectangle(0,0,105.1,41.8), null);


(lib.tx12 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AsIHEIAArEIBSAAIAABCIAJAAQAOgqApgWQAngWA8AAQBfAAAzAzQAyAyAABeIAACHQAABdgyAyQgzAzhfAAQg8AAgngVQgpgWgOgqIgJAAIAGBVIAADMgAqOiiQgiAhAAA/IAABoQAABAAiAhQAjAhBBAAQBAAAAighQAigiAAg/IAAhoQAAhAghggQgigihBAAQhCAAgiAigA1PHEIAArEIBSAAIAABCIAJAAQAOgqApgWQAmgWA8AAQBfAAAzAzQAyAyAABeIAACHQAABdgyAyQgzAzhfAAQg8AAgmgVQgpgWgOgqIgJAAIAFBVIAADMgAzViiQgjAhAAA/IAABoQAAA/AjAiQAiAhBCAAQBAAAAighQAigiAAg/IAAhoQAAg/gighQghgihBAAQhCAAgiAigAPnDSQgxgoAAhKQAAhMAygoQAygqBaAAICqAAIAAgcQAAg3gegZQgggahDAAQhDAAggAaQghAZAAA3IhUAAIAAgKQAAhRA7gvQA7gwBjAAQBlAAA6AwQA5AvAABRIAAFIIhSAAIAAhBIgIAAQgOAiggAVQguAehOAAQhbAAgwgmgAQTBcQAAApAdASQAcATA+gBQBQAAAjgfQAiggAAhJIAAgUIilAAQhnAAAABPgAG1DBQg+g3AAhjIAAkPQAAhrA3g4QA4g3BrAAIDgAAIAABZIjsAAQg8AAgfAhQgeAhAAA/IAAA3IAIAAQAUgmArgUQArgVA8AAQBjAAA1A2QA2A3AABkIAABWQAABig+A4Qg+A3hsAAQhuAAg9g3gAH0iPQgkAiAABHIAABEQAACLCSAAQCOAAAAiLIAAhDQAAiMiQAAQhJAAgjAigAigDSQgxgoAAhKQAAhMAygoQAygqBbAAICoAAIAAgcQAAg3gegZQgfgahEAAQhCAAggAaQggAZAAA3IhVAAIAAgKQAAhRA7gwQA6gvBkAAQBkAAA6AwQA6AvAABRIAAFIIhTAAIAAhBIgIAAQgOAiggAVQgtAehOAAQhaAAgxgmgAh0BcQAAApAdASQAdATA8gBQBRAAAigfQAiggAAhJIAAgUIikAAQhnAAAABPgA9wC/Qg9g5AAhkIgBAAIAAhgQAAhkA/g5QA/g5BqAAQBrAAA+A2QA9A2ADBhIAABLIl5AAIAAAUQAACQCRAAQCCAAANhzIBYAAQgGBdg6AzQg8AzhrAAQhtAAg+g5gA41hHQgJh9iHAAQiHAAgJB9IEgAAIAAAAgEAi6ADkIAAmVIjMAAIAAhPIHwAAIAABPIjMAAIAAGVgAdJDkIAAkMIAFhTIgJAAIjtFfIhaAAIAAnlIBYAAIAAEaQAAAUgBAKIgEA1IAKAAID4ltIBNAAIAAHlgEgkRADkIAAmVIjMAAIAAhPIHwAAIAABPIjNAAIAAGVgAa/ksQhKAAgogkQgpgkAAhBIAAgOIBUAAIAAASQAAA/BHAAIArAAQA+AAAAg/IAAgSIBUAAIAAAOQAABBgnAkQgmAkhFAAg");
	this.shape.setTransform(252.625,45.225);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.tx12, new cjs.Rectangle(0,0,505.3,90.5), null);


(lib.tx11 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAaCQIAAkZIAeAAIAAAkQACgIAGgJQAGgIAGgFQAKgGAGgBQAIgDAKAAQALAAAHADQAIACAJAGQAIAGAFAIIAIASQACAGABAMIAABUQgBAMgCAGIgIASQgGAIgHAFQgKAIgHABQgIACgKAAQgJAAgJgCQgIgDgIgFQgHgFgFgIQgEgGgEgKIAAB3gABVhuQgHABgFAEIgIAIIgGAMQgDAIAAAEIAABIIADALQADAIADADQACAFAGAEQAGAFAGABIANABIANgBQAIgDADgDIAJgJQAFgFABgGQACgHAAgEIAAhIIgCgMQgBgFgFgHIgJgIQgEgEgHgBIgNgBgArhCQIAAkZIAdAAIAAAkQADgIAGgJQAEgGAIgHQAJgGAHgBQAIgDAKAAQALAAAHADQAIACAJAGQAIAGAEAIIAJASQADAJAAAJIAABUQAAAIgDAKIgJASQgGAIgGAFQgKAIgHABQgJACgJAAQgKAAgIgCQgJgDgHgFQgIgFgEgIIgJgQIAAB3gAqmhuIgLAFIgJAIIgFAMQgDAIAAAEIAABIIADALQACAIADADQADAFAGAEQAFAFAGABIANABIANgBQAIgDAEgDIAJgJQAEgFABgGQADgHAAgEIAAhIIgDgMQgBgFgEgHIgJgIQgFgEgHgBIgNgBgAEKA9QgIgCgLgFQgJgFgGgIQgIgHgEgKQgEgJgCgLQgBgFAAgOIABhDQACgKAEgJQADgJAJgJQAGgHAJgFQALgGAIgCQAMgCAJAAQAKAAALACQAJACAKAGQAJAFAGAHQAHAIAFAKQAEAJACAKIABAVIgBBBQgCALgEAJQgFAMgHAFQgGAIgJAFQgKAFgJACIgVACgAEShvQgIACgEACQgFAEgEAFIgHAMQgDAIAAAFIAABIQAAAFADAGIAHALQACAGAHADIAMAGIANABIANgBQAHgCAFgEQAFgDAEgGIAHgLIADgLIAAhIIgDgNIgHgMQgEgFgFgEIgMgEQgEgCgJAAgAt/A8QgLgDgJgIQgKgKgDgKQgEgMAAgMQAAgKADgIQACgKAGgIQAGgGAJgHIARgIIASgEIA1gBIAAgTQAAgKgCgGQgCgHgHgGQgFgFgJgDQgLgDgFAAIgPACQgHABgGAEQgHADgDAHQgEAHAAAHIAAABIgeAAIAAgCQAAgJADgIQABgHAGgIQAIgKAEgDIAPgHQAKgDAHAAIARgCIATACQAIAAAJAEQAKAFAFAGQAIAGAEAIQAEAGADALQACAKAAAIIAACHIgfAAIAAghQgBAFgHALQgKAKgDACQgIAFgIACQgEADgLAAQgNAAgLgDgAtegbIgLACIgLADQgFACgFAFQgFAHgBACQgCAGAAAFQAAAIAEAGQAEAIAFAEQAGAFAIABIAQAAQAJAAAJgDQAIgDAGgGQAGgIACgIQADgHAAgJIAAgVIgiAAIgMABgAHKA9QgKgBgKgGQgJgFgGgIQgFgFgHgMQgEgJgCgLIAAhWQACgKAEgJQAEgKAIgIQAGgHAJgFQAKgGAKgCQAKgCAKAAQAKAAALACQAKACAJAGQAJAFAGAHQAIAKAEAIQAEAJACAKIABAVIAAAkIh2AAIABAXIADALQACAGAEAGQAEAFAGAEIAMAFQAEABAJAAIAPgBQAFgBAJgEQAGgDAEgIQAEgGAAgIIAeAAQAAAKgCAHQgDAIgGAIIgMAMIgPAIQgJADgIABgAHRhwIgNAFIgJAJIgGALIgEANIAAAWIBZAAIAAgWIgEgNIgGgLQgDgFgHgEIgLgFQgFgCgIAAgANNA9IAAirIg6AAIAAgbICSAAIAAAbIg6AAIAACrgAKPgZIgVAAIAABVIgdAAIAAjFIAdAAIAABVIAVAAIA2hVIAiAAIhABjIBABiIgiAAIAAABgAg1A9IAAirIhSAAIAACrIgdAAIAAjGICNAAIAADGgAnqA9IAAirIg7AAIAAgbICTAAIAAAbIg6AAIAACrgAlkgZIAAgbICOAAIAAAbg");
	this.shape.setTransform(93.275,14.375);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.tx11, new cjs.Rectangle(0,0,186.6,28.8), null);


(lib.shad1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(0,0,0,0.749)","rgba(0,0,0,0)"],[0,1],0,0,0,0,0,185).s().p("ArQaoQlLiMkAkAQkBkAiMlMQiRlWAAl6QAAl3CRlYQCMlMEBkAQEAkAFLiNQFZiRF3AAQF4AAFYCRQFMCNEAEAQEAEACNFMQCRFYAAF3QAAF6iRFWQiNFMkAEAQkAEAlMCMQlXCSl5AAQl3AAlZiSg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.shad1, new cjs.Rectangle(-185,-185,370,370), null);


(lib.s3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ANoCKIAAkPIAdAAIAAAkQADgIAEgIQAGgIAHgFQAIgFAGgCQAKgCAIAAQAKAAAIACQAJACAIAGQAHAGAEAIQAEAEAEANIAFARIAABPIgFASIgIARQgGAKgFADQgLAHgGACQgLADgHAAQgIAAgKgDQgIgCgGgFQgGgFgHgIQgFgHgCgJIAABzgAOihsQgFAAgHAEQgFADgEAHQgDAEgCAGIgDANIAABFIADALIAFALIAJAJQAGAFAGABIANABIALgBQAEgBAIgFQAGgEACgFQADgEACgHIADgLIACgNIAAgsIgCgMIgDgNIgFgKIgIgKQgEgDgIgBIgLgCgAMnB0IAAg6IhmAAIAAA6IgdAAIAAhUIALAAQAHgQACgGIAFgYQACgKAAgNIABhgIByAAIAAClIARAAIAABUgALagmQAAANgCALIgEAXQgEAOgDAJIBKAAIAAiMIg8AAgAiVB0IAAg6IhmAAIAAA6IgcAAIAAhUIAKAAQAHgLACgLIAGgYQABgKAAgNIABhgIBzAAIAAClIARAAIAABUgAjhgmQAAANgCALIgFAXQgCANgFAKIBLAAIAAiMIg9AAgARCA7QgJgCgLgKQgIgHgDgMQgEgLAAgLQAAgJACgHQACgKAGgHQAIgKAGgDQAKgFAHgDIASgDIA1gCIAAgSQgBgJgCgHQgCgGgHgGQgFgEgJgEQgIgCgIAAIgNABQgGABgIAEQgFAEgFAHQgDAGAAAHIAAAAIgcAAIAAgBQAAgJACgHQACgJAGgGQADgFAJgHQAFgEAJgEIARgEIAQgBIASABQAIAAAIAFQALAEAFAGQAGAFAFAJQAEAGACALQACAIAAAJIAACDIgcAAIAAggIgJAPQgEAFgIAHQgHAEgJADIgRABQgHAAgQgDgARigbIgMACIgKADIgKAGQgDAEgCAGQgDAFAAAEQAAAIAEAHQACAGAHAEQAJAGAEABIAQABQAJAAAIgDQAKgEAEgGQAEgEAFgKQACgIAAgHIAAgVIgiAAIgKAAgAInA7QgLgBgIgGQgKgGgEgGQgHgGgFgLQgEgKgBgJIAAhUQABgKAEgIQAEgLAIgGQAJgKAFgDQAJgFAKgCQAKgCAKAAQAKAAAKACQAJACAJAFQAKAGAFAHQAHAGAEALQAFAKAAAIIACA4IhzAAIABAVIACALQADAHAFAEQADAGAFADIALAFIANACIAPgCIANgFQAIgFADgFQAEgHAAgIIAdAAQgBAKgDAHQgDAKgEAFQgEAGgIAGIgPAIQgIADgIABQgIADgJAAQgKAAgKgDgAIuhsQgFABgGAEQgEACgFAHQgFAEgCAGQgDAJAAAEIAAAVIBVAAIAAgVIgDgNQgCgFgEgFIgKgJQgHgEgEgBIgMgBgAu7A9QgMgCgGgCQgGgBgJgFQgHgEgFgHQgGgGgDgHQgDgIAAgJIAAgCIAdAAIAAABQAAAGACAEIAGAHIAIAEIAKAEIATACIAPgBQAGgBAJgGQAHgEADgGQAEgHABgJIgCgIQgDgIgDgCIgIgGIgKgDIgKgCIgggBIAAgaIAfgBIAJgCIAIgDIAHgGIAFgHIABgJQAAgHgDgHQgDgFgGgFIgNgFIgNgBIgOABQgHACgFADQgGADgDAGQgFAFABAGIAAABIgeAAIAAgCQAAgJAEgHQACgGAGgHQAGgIAFgDIAPgGIAPgEIAgAAIAQAEIAPAHIALALQAGAGABAKQADAKAAAFIgCAOQAAAFgFAGQgFAHgEACQgEADgIAEQAGABAIAGIAKAKQAGAFACAHQACAJAAAGQAAAKgCAIQgCAJgGAHQgGAHgGAEQgFADgLAFQgEABgOADQgIAEgLAAgAE+A7IAAjAIAcAAIAABQIBQAAIAAhQIAdAAIAAC/IgdAAIAAhVIhQAAIAABWgAAYiFIBHAAIAPAAIAPADQAJAFAFADQAFAEAFAHQAEAHACAIQACAGABAJQAAAHgCAFQgBAHgEAEQgDAFgGAFIgKAHQAIACAGAEIAMAKQADAEAEAJQACAIAAAGQAAAJgCAIQgCAHgGAJQgGAHgHAEQgKAGgFACQgGACgLABIhYABgAA0AgIA2gBIAJgCIAJgDIAIgGQAFgDAAgFIACgKIgCgIQgBgGgEgEIgIgGIgJgDIgJgCIg2AAgAA1g1IArAAIAMgBIAMgGQADgBAEgIQADgGAAgFQAAgIgDgEQgCgFgFgFIgMgEIgMgCIgrAAgAlYA6IAAhKIgiAAIgyBKIgiAAIAyhKQgLgCgIgFQgLgGgDgHQgHgJgCgJQgCgLAAgKIABgQQABgHAEgIQAEgGAGgGIANgJIAPgFIAQgBIBQAAIAAC/gAmYhpQgHACgEAGQgGAGgBAEIgBANIABANQACAHAFAEQADAEAIADQAFACAHAAIAzAAIAAhCIgzAAQgHAAgFACgAqQAgIALgCQAEgBADgGIAFgIIAEgUIABiCICBAAIAADAIgfAAIAAilIhFAAIgDB3IgEAPQgFAMgCACQgEAGgHAFQgLAFgEABIgRABgAssA6IAAi/ICBAAIAAAZIhkAAIAACmgAyqiFIBXAAIAPADQAIAEAFAEQAGAFAEAGQAEAHADAIQACAHAAAIIgCAMQAAAHgEAEQgDAGgGAEIgKAHIAOAGIALAKQAEAEACAJQACAIAAAGQAAAJgCAIQgBAHgGAJQgFAHgIAEIgPAIQgGACgLABIhYABgAyNAgIA1gBIAKgCIAJgDIAIgGQADgEABgEIACgKIgCgIQgBgFgDgFIgIgGIgJgDIgKgCIgLAAIgqAAgAyNg1IA4gBIALgGQAEgCAEgHQACgGAAgFQAAgIgCgEQgCgEgGgGIgLgEIgNgCIgrAAg");
	this.shape.setTransform(119.5,13.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.s3, new cjs.Rectangle(0,0,239,27.6), null);


(lib.s1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AihCwIAAkPIAdAAIAAAkIAIgQQAHgJAFgDQAKgHAFgBQAJgCAJAAQAJAAAJACQAJAEAHAFQAGAEAGAJQAFAGADALQACAHACAKIAABQQgBAJgDAIIgIARIgMAOQgHAFgJADQgLADgHAAQgJAAgJgCQgIgCgHgFQgFgEgHgKQgFgGgDgKIAABzgAhnhFQgFAAgGAEQgGAEgDAFQgDADgCAJIgDALIAABFIADAMQABAFAEAFIAJAKQAFAEAGABQAEABAIAAIANgBQAFgBAHgEQAFgFADgFQADgDACgHIAEgMIAAhFIgEgLQgCgIgDgEIgIgJQgGgDgGgBIgNgCgAkjCwIAAhMIgFAAQgKAAgHgDQgJgCgIgGQgGgFgFgJQgEgDgEgOQgCgEgBgNIAAhQIADgRIAIgRQAHgJAEgEIARgJQALgCAGAAIAFAAIAAhNIAcAAIAABNIAEAAQALAAAHACQAJAEAHAFQAGAEAGAJQAFAGADALQACAEACANIAABQIgEARQgDALgFAGIgMAOQgHAFgJADQgLADgHAAIgEAAIAABMgAkHBMIAEAAQAFAAAHgCQADgCAGgFQADgCACgIIAEgLIACgXIAAg2IgCgLIgEgLIgFgKIgJgGQgHgDgFgBIgEAAgAkyhGQgEABgFAFQgDADgDAHIgFAWIAAA3IACAXIADALIAGAJIAJAIQAFABAGAAIAFAAIAAiUIgFAAQgGAAgFADgApKCcIAAg7IiCAAIAAjAIAdAAIAACnIBQAAIAAinIAcAAIAACnIARAAIAABUgAG7BiQgLgDgHgEQgKgGgFgHQgHgHgFgKQgFgKAAgJIgBgUIABg/QABgKAEgJQAGgLAGgGIAPgMQAIgGAKgCQAKgCAKAAQAKAAAKACQAIACAKAGQALAGAEAGQAHAIAFAJQAEAKABAJIACA/IgCAUQgBAKgEAJQgEAJgIAIQgJAJgGAEQgIAFgKACQgKACgKAAQgKAAgKgCgAHChEQgEAAgGAEQgGAEgEAEQgFAGgCAGIgCAMIAABEIACAMQACAFAFAGQADAFAHAEQAGAEAEABQAEABAJAAIANgBQAEgBAHgEQAEgDAEgGQAGgHABgEQADgIAAgEIAAhEIgDgMQgBgFgGgHQgEgFgEgDQgHgEgEAAIgNgBgABIBiQgKgCgIgFQgKgGgFgHQgIgIgEgJQgEgKgBgJIAAhTQABgKAEgJQAFgJAHgIQAJgIAGgEQAKgGAIgCIAUgCQALAAAJACQAKACAIAGQALAGAFAGQAGAGAFALQAFAKAAAJIABA/IgBAUQAAAKgFAJQgFAKgGAHIgQANQgGAEgMADQgJACgLAAQgKAAgKgCgABQhEQgFAAgGAEQgGADgDAFIgIAMIgCAMIAABEIACAMIAIALQADAGAGADQAGAEAFABQAEABAIAAIANgBQAEgBAHgEQAGgEADgFQAEgGADgFQACgIAAgEIAAhEIgCgMQgDgGgEgGQgDgEgGgEIgLgEIgNgBgAKxBhIADieIhNCeIgkAAIAAjAIAdAAIgECfIBOifIAjAAIAADAgADQhfIBXABIAPAEQAIADAGAEQAGAFAEAHQAEAGACAHQACAIAAAIIgBAMQgBAHgEAFQgCAEgGAEIgLAIQAIACAGAEQAHAEAEAFQAFAEADAKQABAHAAAIQAAAIgBAIQgCAJgHAHQgDAGgJAFIgQAIQgFACgMABIhYABgADtBIIA1gCIAKgCIAJgDQACgBAFgFQAFgEAAgEQACgFAAgFQAAgEgCgGQAAgEgFgEIgHgHIgJgDIgKgCIg1gBgADugOIAqAAIANgBQAFgBAGgEQAEgCAEgIQACgGAAgFQAAgHgCgFQgCgGgGgDIgLgFIgNgBIgqAAgAmmBhIAEieIhNCeIgkAAIAAjAIAdAAIgDCfIBMifIAjAAIAADAgAJyh/QgLgDgIgHQgJgIgDgJQgEgLAAgLIAaAAQAAAFACAHQABAGAGAEQADADAIADIALABIAMgBQAFgBAGgFQAEgEACgGQADgJAAgDIAaAAQAAAMgFAKQgEAJgIAIQgHAHgMADQgJADgNAAQgNAAgJgDg");
	this.shape.setTransform(71.7,17.65);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.s1, new cjs.Rectangle(0,0,143.4,35.3), null);


(lib.rr = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("AAA/PMAAAA+f");
	this.shape.setTransform(0,200);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.rr, new cjs.Rectangle(-1,-1,2,402), null);


(lib.ligal = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgIA5IgIgEIgHgGIgEgIIgCgIIgBgJIABgOIAEgMIAYg1IAQAAIgXAyIAHgFIAIgCIAIACQAEACACACIAFAHIADAGIACARIgBAJIgCAIIgEAIIgHAGIgIAEIgJABgAgDAAIgEACQgBABAAAAQgBAAAAABQgBAAAAABQAAAAAAABIgCAEIgCAEIAAAFIAAAIIABAFIACAEIADAFQACACACAAIAEABIAFgBIAEgCIADgFIACgEIABgFIAAgKIgBgGIgCgEIgDgEQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBgBIgFAAg");
	this.shape.setTransform(432.825,6.925);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgEAgIAAgbIgcAAIAAgJIAcAAIAAgbIAJAAIAAAbIAcAAIAAAJIgcAAIAAAbg");
	this.shape_1.setTransform(441.45,7.975);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgdA5IAAhxIAcAAIAIABIAIADIAHAGIAFAHIADAJIAAARIgDAJIgFAGIgHAFIgIAEIgIAAIgMAAIAAAugAgNgBIAMAAIAFAAIAEgDIADgEIACgEIACgKIgCgJIgCgFIgDgDIgEgDIgFgBIgMAAg");
	this.shape_2.setTransform(2.95,7.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgIApIgIgDQgFgDgBgCIgFgHIgCgIIAAgjIACgIIAFgHQABgCAFgDIAIgDIAIgBIAIABIAIADQAFADACACIAEAHIADAIIABAYIguAAIABAJIADAGIAFAFIAGABIAFgBQADAAACgBIADgEQABgCABgDIAQAAIgCAHQgBAEgCADIgGAFIgFADIgIACIgHABgAgGgaIgFAFQgBABgBAFIgCAHIAAACIAeAAIAAgJQgBgEgDgCIgEgFQgDgBgEAAIgGABg");
	this.shape_3.setTransform(9.6,9.025);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAMApIgRgiIgHAAIAAAiIgRAAIAAhRIARAAIAAAjIAHAAIARgjIASAAIgYAoIAYApg");
	this.shape_4.setTransform(16.65,9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AASApIAAhCIgXAAIAAAZIgBARIgBAGIgFAKIgEAEIgFACIgFACIgGAAIAAgOIAEgBIADgCIACgDIABgEIABgJIAAgwIA2AAIAABRg");
	this.shape_5.setTransform(22.925,9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgPAoQgFgBgDgEQgDgCgCgGQgBgEAAgFIABgIQAAgDAEgEQACgDADgCIAHgDIAJgCIAHAAIALAAIgBgMIgDgFIgFgCIgGgBIgDAAIgFACIgEAEIAAAFIAAAAIgQAAIAAgBIABgHQABgDACgDIAFgFIAHgEIAHgBIAFgBIAIABIAHACIAHAEIAEAGIADAHIABAHIAAA2IgPAAIAAgNQgBAEgCACIgGAFIgGADIgFABQgGAAgEgCgAgDAGIgEABIgEACIgBAEIgBAEIABAFIADADIAFACIAEABIAGgBIAFgDQACgCABgEIABgNIgLAAg");
	this.shape_6.setTransform(30.05,9.025);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AASApIAChBIgOBBIgLAAIgOhBIACBBIgOAAIAAhRIAUAAIALA1IALg1IAVAAIAABRg");
	this.shape_7.setTransform(36.925,9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgPAoQgFgBgDgEQgCgCgCgGQgCgEAAgFIABgIQABgFACgCQADgDAEgCIAHgDIAIgCIAGAAIAMAAIAAgHIgBgFIgDgFIgFgCIgGgBIgDAAIgFACIgDAEIgBAFIAAAAIgQAAIAAgBIABgHQAAgDADgDIAFgFIAHgEIAGgBIAGgBIAIABIAIACIAGAEIAEAGIADAHIABA9IgPAAIAAgNIgEAGIgEAFIgHADIgGABQgFAAgEgCgAgDAGIgEABIgDACIgDAEIgBAEIACAFIADADIAFACIAEABIAGgBIAFgDIADgGIABgGIAAgHIgMAAg");
	this.shape_8.setTransform(43.7,9.025);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgFANQgCAAgDgDQgCgBgBgDIAAgGIAAgFQABgCACgDQADgCACgBIAFAAIAFAAQAEABABACQADADAAACIABAFIgBAGQgBADgCABQgBACgEABIgFABg");
	this.shape_9.setTransform(50.625,11.775);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgcA5IAAhxIAcAAIAHABIAJADIAGAGQADADACAEIACAJIAAARIgCAJIgFAGIgGAFIgJAEIgHAAIgNAAIAAAugAgNgBIANAAIADAAQADgBACgCQAAAAABgBQAAAAABgBQAAAAAAgBQABAAAAgBIACgEIABgFIAAgKIgBgEIgCgFQAAAAgBgBQAAAAAAgBQgBAAAAgBQgBAAAAAAQgCgCgDgBIgDgBIgNAAg");
	this.shape_10.setTransform(64.525,7.35);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgIApIgIgDIgGgFQgDgDgBgEQgCgCgBgGIgBgJIAAgRIABgJIADgIQABgEADgDIAGgFIAIgDIAIgBIAIABIAJADIAGAFQADADABAEIADAIIABAJIAAAPIgtAAIAAAJIADAGQACADADACIAGABIAFgBQADAAACgBIAEgEQABgCAAgDIAPAAIgBAHIgDAHIgFAFIgGADIgHACIgIABgAgGgaQgDACgCADIgDAGIAAAJIAeAAIAAgCIgBgHQgBgEgDgCQgBgDgDgCQgDgBgEAAQgCAAgEABg");
	this.shape_11.setTransform(71.15,9.025);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAMApIgSgiIgHAAIAAAiIgPAAIAAhRIAPAAIAAAjIAHAAIASgjIARAAIgXAoIAXApg");
	this.shape_12.setTransform(78.225,9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AARApIAAhCIgWAAIAAAfIgCARIgCAFIgDAFIgEAEIgFACIgGACIgFAAIAAgOIAEgBIADgCIACgDIACgIIAAgFIAAgDIAAgtIA2AAIAABRg");
	this.shape_13.setTransform(84.5,9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgPAoQgFgBgDgEQgDgCgCgGQgBgEAAgFIABgIQABgFACgCIAGgFIAIgDIAIgCIAHAAIALAAIAAgHIgBgFIgDgFIgFgCIgFgBIgEAAIgFACIgDAEIgCAFIAAAAIgPAAIAAgBIABgHIADgGIAFgFIAGgEIAHgBIAHgBIAHABIAHACIAHAEIAFAGIADAHIAAA9IgPAAIAAgNIgEAGIgFAFIgGADIgGABIgJgCgAgDAGIgEABIgDACIgDAEIgBAEIACAFIADADIAFACIAEABIAGgBIAFgDQACgCABgEIABgGIAAgHIgLAAg");
	this.shape_14.setTransform(91.625,9.025);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AARApIADhBIgPBBIgKAAIgOhBIADBBIgPAAIAAhRIAUAAIALA1IAMg1IAUAAIAABRg");
	this.shape_15.setTransform(98.55,9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgHApIgIgDIgHgFIgFgHIgCgIIAAgjIACgIIAFgHIAHgFIAIgDIAHgBIAJABQAGABACACIAGAFQADADACAEIACAIIAAAjIgCAIQgCAEgDADIgGAFIgIADIgJABgAgGgaIgFAFIgCAGIgBAHIAAARIABAHIACAGIAFAFIAGABIAHgBQADgCACgDIADgGIAAgHIAAgYQgBgEgCgCQgCgDgDgCQgDgBgEAAg");
	this.shape_16.setTransform(105.375,9.025);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AATA1IAAgYIgkAAIAAAYIgQAAIAAgmIAEAAIAEgJIACgIIABgyIAxAAIAABDIAHAAIAAAmgAgIgCIgDAIQAAAFgDAEIAaAAIAAg0IgTAAg");
	this.shape_17.setTransform(112.25,10.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgPAoQgFgBgDgEQgDgCgCgGQgBgEAAgFIABgIQAAgDADgEQADgDADgCIAIgDIAHgCIAIAAIALAAIAAgHIgBgFIgDgFIgFgCIgGgBIgEAAIgEACQgBABAAAAQgBAAAAABQgBAAAAABQAAAAAAABIgCAFIAAAAIgPAAIAAgBIABgHIADgGIAFgFIAGgEIAHgBIAGgBIAIABIAHACIAHAEIAFAGIACAHIABAHIAAA2IgPAAIAAgNIgEAGIgFAFIgGADIgGABgAgHAHIgEACIgCAEIgBAEIACAFIADADIAFACIAEABIAGgBIAFgDQACgCABgEIABgGIAAgHIgLAAg");
	this.shape_18.setTransform(119.025,9.025);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgHApIAAhCIgWAAIAAgPIA7AAIAAAPIgWAAIAABCg");
	this.shape_19.setTransform(125.95,9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgIApIgIgDIgGgFIgFgHIgCgIIAAgjIACgIIAFgHIAGgFIAIgDIAIgBIAIABIAIADQAFADACACIAEAHIADAIIAAAYIgtAAIABAJIADAGIAFAFIAGABIAFgBQADAAACgBIADgEIACgFIAPAAIgBAHQgBAEgCADIgGAFIgFADIgIACIgHABgAgGgaIgFAFQgBABgCAFIgBAHIAAACIAeAAIAAgJQgBgEgDgCIgEgFQgDgBgEAAIgGABg");
	this.shape_20.setTransform(132.8,9.025);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AASApIAAhCIgXAAIAAAZIgBARIgBAGIgFAKIgEAEIgFACIgFACIgGAAIAAgOIAEgBIADgCIACgDIABgEIABgJIAAgwIA2AAIAABRg");
	this.shape_21.setTransform(139.275,9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgdgoIAQAAIAAAeIAYABIAHACIAFAEIAFAFIACAGIAAAHIAAAHIgCAHIgFAFIgFAEIgHACIgoABgAgNAbIARAAIAFgBIADgDIACgDIABgFIgBgEIgCgFIgDgCIgFgBIgRAAg");
	this.shape_22.setTransform(146.525,9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgFApQgCgBgDgCIgDgFIAAgGIAAgFIADgFQADgDACAAIAFgBIAGABQACAAADADIACAFIABAFIgBAGIgCAFQgDACgCABIgGABgAgFgNIgFgDIgDgFIAAgFIAAgGIADgFIAFgDIAFgBIAGABIAFADIACAFIABAGIgBAFIgCAFIgFADIgGABg");
	this.shape_23.setTransform(153.325,9.025);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAOA5IAAhkIgbAAIAABkIgPAAIAAhxIA5AAIAABxg");
	this.shape_24.setTransform(167,7.35);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AARA5IgFgaIgXAAIgFAaIgQAAIAYhxIARAAIAYBxgAgBgaIgHAqIARAAIgJgxIgBAHg");
	this.shape_25.setTransform(173.875,7.35);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgIA6IgIgDIgHgFQgDgEgBgDIgDgIIAAhFIADgIQABgDADgDIAHgGIAIgCIAIgBIAIABIAIACIAGAGQAEADABADIACAIIABAJIAAAzIgBAJQgBAFgBADQgBADgEAEIgGAFIgIADIgIABgAgGgqQgEABgBADQgCACgBAEIgBAHIAAAzIABAHIADAGQABACAEACIAGABIAGgBQADgBACgDIADgGIABgHIAAgzIgBgHIgDgGQgCgDgDgBQgCgCgEAAQgEAAgCACg");
	this.shape_26.setTransform(180.75,7.35);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAMATIgIgIIgIgIIAAgFIAIgHIAIgJIAKgVIAMAEIgKATQgGALgGAFQAGAGAGALIAKATIgMAEgAgRATIgHgIQgEgFgFgDIAAgFIAJgHIAHgJIALgVIAKAEIgIATQgHALgGAFQAGAGAHALIAIATIgKAEg");
	this.shape_27.setTransform(194.4,7.775);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgbA5IAAhxIA3AAIAAANIgnAAIAABkg");
	this.shape_28.setTransform(201.55,7.35);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgPAoQgFgBgDgEQgDgCgCgGQgBgEAAgFIABgIQABgFACgCIAGgFIAIgDIAIgCIAHAAIALAAIAAgHIgBgFIgDgFIgFgCIgFgBIgEAAIgFACIgDAEIgCAFIAAAAIgPAAIAAgBIABgHIADgGIAFgFIAGgEIAHgBIAHgBIAHABIAHACIAHAEIAFAGIADAHIAAA9IgPAAIAAgNIgEAGIgEAFIgHADIgGABIgJgCgAgDAGIgEABIgDACIgDAEIAAAEIABAFIADADQABABAAAAQABAAAAABQABAAABAAQAAAAABAAIAEABIAGgBIAFgDIADgGIABgGIAAgHIgLAAg");
	this.shape_29.setTransform(208.025,9.025);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgGApIgHgBQgEgBgDgCQgDgBgDgEIgEgGIAAgHIAAgBIAPAAIAAABQAAAAAAABQAAABAAAAQABABAAAAQAAABABAAIAEADIAFACIAKgBQACAAADgBIADgEIACgGIgBgDIgBgDIgDgDIgIgCIgMAAIAAgMIAJAAIAEgBIAEgBIAEgEIACgEIgCgFQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAgBgBAAIgEgCIgFAAIgDAAIgFACIgEADIAAAEIAAABIgQAAIAAgCIABgGIADgGIAFgFQADgCAEgBQADgBADAAIAGgBIAHABIAHABIAGAEIAFAEQADADAAAEIABAHIAAAFIgDAFIgDADIgEADIAFACIAFAEIACAGIABAGIgBAHIgEAHIgFAFIgHADIgIACIgHABg");
	this.shape_30.setTransform(215,9.025);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AAOApIAAhCIgbAAIAABCIgPAAIAAhRIA5AAIAABRg");
	this.shape_31.setTransform(221.8,9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgdA6IAAhyIAQAAIAAAPIACgGIAGgGQABgCAEgBIAGgBIAIABQAEACADACIAEAGIAEAHIABAHIAAAhIgBAHIgEAHIgEAGQgDADgEAAIgIACIgGgBIgFgEIgGgFIgCgGIAAAwgAgFgqIgGAFIgCAGIAAAHIAAAYIACAGIAGAFIAFABIAGgBIAGgFIACgGIAAgGIAAgZIgCgGIgGgFQgDgBgDAAQgCAAgDABg");
	this.shape_32.setTransform(228.7,10.625);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgHApIgIgDIgHgFIgFgHIgCgIIAAgjIACgIIAFgHIAHgFIAIgDIAHgBIAJABIAHADIAHAFIAFAHIACAIIAAAjIgCAIIgFAHIgHAFIgHADIgJABgAgGgaIgFAFIgCAGIgBAHIAAARIABAHIACAGIAFAFIAGABIAHgBQADgCACgDIADgGIAAgHIAAgYQgBgEgCgCQgCgDgDgCQgDgBgEAAg");
	this.shape_33.setTransform(235.475,9.025);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AARApIAChBIgNBBIgLAAIgOhBIACBBIgOAAIAAhRIAUAAIALA1IAMg1IAUAAIAABRg");
	this.shape_34.setTransform(242.35,9);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AAOApIAAgjIgbAAIAAAjIgQAAIAAhRIAQAAIAAAhIAbAAIAAghIAQAAIAABRg");
	this.shape_35.setTransform(256.025,9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgHApIgIgDQgGgDgBgCIgFgHIgDgIIAAgjIADgIIAFgHQABgCAGgDIAIgDIAHgBIAIABIAIADQAFADABACIAGAHIACAIIAAAYIgsAAIAAAJIADAGIAFAFIAGABIAFgBQABAAAAAAQABAAABAAQAAAAABgBQAAAAABAAQADgCAAgCQACgCgBgDIAQAAIgBAHQgBAEgCADIgFAFIgHADIgHACIgHABgAgGgaIgFAFQgBABgCAFIAAAHIAAACIAdAAIgBgJIgCgGIgGgFIgGgBg");
	this.shape_36.setTransform(262.9,9.025);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgHBKIAAggIgIgBIgHgEIgFgFIgDgHIgCgIIAAgIIAAgZIACgIIADgHIAFgFIAHgEIAIgBIAAggIAPAAIAAAgIAIABIAHAEIAFAFIADAHIACAIIAAAZIAAAIIgCAIIgDAHIgFAFIgHAEIgIABIAAAggAAHAeIABAAIAEgBIADgDIACgEIACgEIAAgEIAAgbIAAgEIgCgEIgCgEIgDgDIgEgBIgBAAgAgLgcIgDADIgCAEIgCAEIAAAEIAAAbIAAAEIACAEIACAEIADADIAEABIABAAIAAg7IgBAAg");
	this.shape_37.setTransform(269.725,9.025);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgHApIAAhCIgWAAIAAgPIA8AAIAAAPIgXAAIAABCg");
	this.shape_38.setTransform(276.55,9);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgdgoIAPAAIAAAeIAZABIAHACIAFAEIAEAFIADAGIAAAHIAAAHIgDAHIgEAFIgFAEIgHACIgoABgAgOAbIASAAIAFgBIADgDIACgDIABgFIgBgEIgCgFIgDgCIgFgBIgSAAg");
	this.shape_39.setTransform(283.475,9);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgDAkQADgLAFgIQAFgKAHgHQgHgGgFgKQgFgIgDgLIAKgEIAEALIAGAKIAIAJQAFAEAEADIAAAFQgFADgEAFIgIAIIgGAKIgEALgAghAkQAEgLAFgIQAGgKAHgHQgHgGgGgKQgFgIgEgLIAMgEIAEALIAGAKIAIAJIAHAHIAAAFIgHAIIgIAIIgGAKIgEALg");
	this.shape_40.setTransform(290.3,7.775);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AADBFIgJgLIgIgNQgEgJgBgGIgDgPIgBgPIABgOIADgPQABgGAEgJIAIgNIAJgLIAOgJIAHAMQgJAFgGAHQgGAJgDAHIgGATIgCASQABAKABAJIAGATQADAHAGAJQAGAHAJAFIgHAMIgOgJg");
	this.shape_41.setTransform(304.15,7.775);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AAOA5IADhWIgdBWIgQAAIAAhxIAPAAIgCBWIAbhWIARAAIAABxg");
	this.shape_42.setTransform(310.8,7.35);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AAOA5IAAg0IgbAAIAAA0IgPAAIAAhxIAPAAIAAAwIAbAAIAAgwIAPAAIAABxg");
	this.shape_43.setTransform(317.65,7.35);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AAOA5IAAg0IgbAAIAAA0IgPAAIAAhxIAPAAIAAAwIAbAAIAAgwIAPAAIAABxg");
	this.shape_44.setTransform(324.5,7.35);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AgHA5IgIgCIgGgFIgEgGIgDgHIgCgIIAQAAIABAGQABACADADIAEADIAFABIAFgBIAEgDIADgFIACgKIAAgKIgBgGIgBgFIgCgEIgFgCIgEgBIgFAAIgEACIgDADIgCAFIgPAAIAAhAIA2AAIAAAOIgnAAIAAAcIAHgCIAHAAIAJABQADABAFADQADACACAFIAFAHIABAJIABAJIgBAJIgBAJIgFAIIgGAHIgIADIgJACg");
	this.shape_45.setTransform(338.25,7.425);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgHA5IgIgCIgFgFIgGgGIgCgHIgBgIIAPAAIABAGQABACADADIAEADIAFABIAFgBIAEgDIADgFIADgKIAAgKIgCgGIgBgFIgDgEIgDgCIgGgBIgEAAIgEACIgDADIgCAFIgPAAIAAhAIA2AAIAAAOIgnAAIAAAcIAHgCIAGAAIAJABQAFABAEADQADACADAFIAEAHIABAJIABAJIgBAJIgBAJIgEAIIgHAHIgIADIgJACg");
	this.shape_46.setTransform(345.1,7.425);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgHA6IgIgDIgHgFIgFgHIgCgIIAAhFIACgIIAFgGIAHgGIAIgCIAHgBIAJABIAIACIAGAGQADADACADIACAIIAABFIgCAIQgCADgDAEIgGAFIgIADIgJABgAgOATIAAAHIABAHIACAGIAFAEIAGABIAHgBQADgCACgCIADgGIAAgkgAgGgqQgCABgDADIgCAGIgBAHIAAAeIAdgXIAAgOQgBgEgCgCQgCgDgDgBQgDgCgEAAQgCAAgEACg");
	this.shape_47.setTransform(351.875,7.35);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AAGA5IAAgdIgjAAIAAgNIAihHIAPAAIgiBHIAUAAIAAgZIAPAAIAAAZIAJAAIAAANIgJAAIAAAdg");
	this.shape_48.setTransform(358.675,7.35);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgHA6IgIgDIgHgFIgFgHIgCgIIAAhFIACgIIAFgGIAHgGIAIgCIAHgBIAJABIAHACQAFADACADQADADACADIACAIIAABFIgCAIQgCADgDAEQgCACgFADIgHADIgJABgAgOATIAAAHIABAHIACAGIAFAEIAGABIAHgBQADgCACgCIADgGIAAgkgAgGgqQgCABgDADIgCAGIgBAHIAAAeIAdgXIAAgOQgBgEgCgCQgCgDgDgBQgDgCgEAAQgCAAgEACg");
	this.shape_49.setTransform(365.575,7.35);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgHA6IgIgDIgHgEIgFgHIgDgHIgBgIIAAgBIAQAAIAAAAIABAHQABAEACACIAGADIAFAAIAHgBIAFgDIADgHIABgHIgBgGQAAgCgCgDQAAgDgDgCIgFgDIgFgBIgFgBIAAgNIAJgBIAEgDIADgFQACgCAAgCIABgGIgBgGIgDgFQgBgDgDgCQgCgBgEAAIgFABIgEAEIgDAFIAAAGIAAABIgQAAIAAgBIABgIIACgIIAFgFIAGgFQAEgDADABIAHgBIAIABQAFAAACACQADACADADQADACACAEQABACABAGIABAIIgBAIIgDAHQgBADgDADIgHAFIAIAEIAFAHIAEAIIABAIIgBAJQgBAEgCAEQgCAEgDADIgHAFIgIADIgIABg");
	this.shape_50.setTransform(372.475,7.35);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgIA5IgIgEIgHgGIgEgIIgCgIIgBgJIABgOIAEgMIAYg1IAQAAIgXAyIAHgFIAIgCIAIACQAEACACACIAFAHIADAGIACARIgBAJIgCAIIgEAIIgHAGIgIAEIgJABgAgDAAIgEACQgBABAAAAQgBAAAAABQgBAAAAABQAAAAAAABIgCAEIgCAEIAAAFIAAAIIABAFIACAEIADAFQACACACAAIAEABIAFgBIAEgCIADgFIACgEIABgFIAAgKIgBgGIgCgEIgDgEQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBgBIgFAAg");
	this.shape_51.setTransform(379.275,7.425);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgHA6IgIgDIgHgEIgFgHIgDgHIgBgIIAAgBIAQAAIAAAAQAAAEABADQABAEACACIAGADIAFAAIAHgBQADgBACgCIADgHIABgHIgBgGIgCgFIgDgFIgFgDIgFgBIgFgBIAAgNIAJgBIAEgDIADgFQACgCAAgCIABgGIgBgGIgDgFQgBgDgDgCQgCgBgEAAIgFABIgEAEIgDAFIgBAGIAAABIgPAAIAAgBIABgIIACgIIAFgFIAGgFQAEgDADABIAHgBIAIABIAHACQADACADADQADACACAEIACAIIABAIIgBAIIgDAHQgBADgDADIgHAFIAHAEQAEAEACADIAEAIIABAIIgBAJQgBAEgCAEQgCAEgDADIgHAFIgIADIgIABg");
	this.shape_52.setTransform(386.175,7.35);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgHA6IgIgDIgHgEIgFgHIgDgHIgBgIIAAgBIAQAAIAAAAQAAAEABADQABAEACACIAGADIAFAAIAHgBQADgBACgCIADgHIABgHIgBgGIgCgFIgDgFIgFgDIgFgBIgFgBIAAgNIAJgBIAEgDIADgFQACgCAAgCIABgGIgBgGIgDgFQgBgDgDgCQgCgBgEAAIgFABIgEAEIgDAFIgBAGIAAABIgPAAIAAgBIABgIIACgIIAFgFIAGgFQAEgDADABIAHgBIAIABIAHACQADACADADQADACACAEIACAIIABAIIgBAIIgDAHIgEAGQgDAEgEABIAHAEQAEAEACADQADAEAAAEIACAIIgBAJQgBAEgCAEIgFAHIgHAFIgIADIgIABg");
	this.shape_53.setTransform(393.025,7.35);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgHA6IgIgDIgHgEIgFgHIgDgHIgBgIIAAgBIAQAAIAAAAQAAAEABADQABAEACACIAGADIAFAAIAHgBQADgBACgCIADgHIABgHIgBgGIgCgFIgDgFIgFgDIgFgBIgFgBIAAgNIAJgBIAEgDIADgFIACgEIAAgGIAAgGQgBgEgCgBQgBgDgDgCIgGgBIgFABIgEAEIgDAFIgBAGIAAABIgPAAIAAgBIABgIIACgIIAFgFQACgDAEgCQAEgDADABIAHgBIAIABIAHACIAGAFQADACACAEIACAIIABAIIgBAIIgDAHIgFAGQgCADgEACIAHAEQAEAEACADQADAEAAAEIACAIIgBAJIgDAIQgCAEgDADIgHAFIgIADIgIABg");
	this.shape_54.setTransform(399.875,7.35);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgXBCQAIgEAHgIQAHgIACgIQAEgKACgJQABgJAAgKIgBgSQgCgJgEgKQgCgIgHgIQgHgIgIgEIAIgMIAMAJQAGAGAEAFQAFAGADAHIAFAPIADAPIABAOIgBAPIgDAPIgFAPQgEAIgEAFQgEAFgGAGQgFAFgHAEg");
	this.shape_55.setTransform(406.475,7.775);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AhaBbQglgmAAg1QAAg0AlgmQAmglA0gBQA1ABAmAlQAlAmAAA0QABA1gmAmQgmAlg1ABQg0gBgmglgAhThTQgjAjABAwQgBAxAjAjQAjAjAwAAQAxAAAigjQAkgjgBgxQABgwgkgjQgigjgxAAIAAAAQgwAAgjAjg");
	this.shape_56.setTransform(436.8,7.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ligal, new cjs.Rectangle(0,-5.1,449.7,25.700000000000003), null);


(lib.l = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EjqXAAFIAAgJMHUvAAAIAAAJg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.l, new cjs.Rectangle(-1500,-0.5,3000,1), null);


(lib.gazprom_logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhrCcIAAhJIGvAAIAABJgAEVCPIALAAQAJAAADgDQAEgCAAgIIAAgEQAAgIgDgCQgDgDgJAAIgBAAIAAgSIgLAAgAC5BoIAJAAIAAAnIALAAIAAgnIAIAAIAAgJIgcAAgABnBjQgJAAgDACQgEADAAAHIAAAPQAAAMAQAAIAAAFIAKAAIAAgFQAQAAAAgMIAAgPQAAgHgEgDQgDgCgJAAIAAgEIgKAAgAADCPIAaAAIAAgJIgOAAIAAgMIANAAIAAgJIgNAAIAAgJIAOAAIAAgJIgaAAgAhHB6IAAAVIALAAIAAgwIgLAAIAAASIgGAAIAAgSIgLAAIAAAwIALAAIAAgVgAkjB9QggghAAgtQAAgtAggeQAfggAtAAIAABQQgZABgSARQgEAEgDAFQgMASACAWQACAWAPAQQASASAZAAQAaAAARgSIAAAAQAJgJAAgNQAAgNgJgIQgJgKgMABQgNgBgJAKIAAgjIBPAAIAABKQghAjguAAQgtAAgfgfgAEgCGIAAgMIACAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAGQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAgABxCBIAAgWIACAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAAAQQAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAgABlCBQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAgQQAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAIABAAIAAAWgAEvAvIAAhDIgBAAIgLBDIgQAAIgLhDIgBAAIAABDIgUAAIAAhsIAbAAIANBLIAOhLIAbAAIAABsgADGAvQgQAAAAgTIAAhGQAAgSAQgBIARAAQAPABAAASIAABGQAAATgPAAgADKgrIAABIQAAAEAEABQAGgBgBgEIAAhIQAAgEgFAAQgDAAgBAEgAB6AvIAAhsIAhAAQARABAAASIAAAiQAAASgRAAIgMAAIAAAlgACPgBIAFAAQAEAAAAgGIAAgjQAAgFgEAAIgFAAgABYAvIAAheIgJAAIAABeIgUAAIAAhsIAwAAIAABsgAANAvQgOAAAAgTIAAgTIATAAIAAAUQAAAEAEABQADgBAAgEIAAgZQAAgGgIAAIgJAAIAAgMIAJAAQAEAAACgCQACgBAAgFIAAgVQAAgBAAgBQgBgBAAAAQgBgBAAAAQgBAAgBAAQgBAAAAAAQgBAAAAABQAAAAgBABQAAABAAABIAAARIgTAAIAAgPQAAgUAOAAIARAAQAPAAAAAUIAAARQAAAQgOgBIAAABQAOgBAAAPIAAAWQAAATgPAAgAgfAvIgCgdIgJAAIgCAdIgVAAIALhsIAhAAIALBsgAgqAHIAJAAIgEg2IgBAAgAhrAvIAAhsIAnAAIAAAOIgSAAIAABegAjAAKQgJgXgDgWQgEgkAKgjQAHgXAQgaIACACQASAeAGAYQAHAigEAhQgGArgXAeQgKgNgHgSgAi0gYQgEALABAMQAAARAIASQAJgRAAgUQgBgTgIgOQgCADgDAJgAjAhiQgFASgBATQAAAXADATQAAgaAEgRQAGgdAKgQQAFAHAFAOQAFAOACAKQAFAXgCATQADgJABgVQAAgagHgXQgFgVgMgUQgJAQgIAag");
	this.shape.setTransform(32.375,15.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.gazprom_logo, new cjs.Rectangle(0,0,64.8,31.2), null);


(lib.bg_pic = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.instance = new lib.terra_bg_970();
	this.instance.setTransform(-631,-163,1,0.9999);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.bg_pic, new cjs.Rectangle(-631,-163,1262,325), null);


(lib.bg_main = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0070BA").s().p("EjDGATsMAAAgnXMGGNAAAMAAAAnXg");
	this.shape.setTransform(1248.725,125.975);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.bg_main, new cjs.Rectangle(0,0,2497.5,252), null);


(lib.bg_blue = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0070BA").s().p("ApDEiIAApDISHAAIAAJDg");
	this.shape.setTransform(970,193.9,8.3622,4.3102,0,0,0,58,16);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.bg_blue, new cjs.Rectangle(0,0,970,250), null);


(lib.tx13 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.s1 = new lib.s1();
	this.s1.name = "s1";
	this.s1.setTransform(71.7,17.7,1,1,0,0,0,71.7,17.7);

	this.s2 = new lib.s3();
	this.s2.name = "s2";
	this.s2.setTransform(119.5,50.75,1,1,0,0,0,119.5,13.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.s2},{t:this.s1}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.tx13, new cjs.Rectangle(0,0,239,64.6), null);


(lib.tx1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// tx1_2
	this.tx1_2 = new lib.tx12();
	this.tx1_2.name = "tx1_2";
	this.tx1_2.setTransform(252.6,65.9,1,1,0,0,0,252.6,45.2);

	this.timeline.addTween(cjs.Tween.get(this.tx1_2).wait(1));

	// tx1_3
	this.tx1_3 = new lib.tx13();
	this.tx1_3.name = "tx1_3";
	this.tx1_3.setTransform(385.75,136.6,1,1,0,0,0,119.5,36.1);

	this.timeline.addTween(cjs.Tween.get(this.tx1_3).wait(1));

	// tx1_1
	this.tx1_1 = new lib.tx11();
	this.tx1_1.name = "tx1_1";
	this.tx1_1.setTransform(93.2,14.3,1,1,0,0,0,93.2,14.3);

	this.timeline.addTween(cjs.Tween.get(this.tx1_1).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.tx1, new cjs.Rectangle(0,0,505.3,165.1), null);


(lib.logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// gazprom_logo
	this.logo = new lib.gazprom_logo();
	this.logo.name = "logo";
	this.logo.setTransform(39.5,4.2,1.1734,1.173,0,0,0,32.2,15.5);

	this.timeline.addTween(cjs.Tween.get(this.logo).wait(1));

	// gazprom_logo_bg
	this.bg_blue = new lib.bg_blue();
	this.bg_blue.name = "bg_blue";
	this.bg_blue.setTransform(71.5,17.6,0.1125,0.232,0,0,0,745.4,164.7);

	this.timeline.addTween(cjs.Tween.get(this.bg_blue).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-12.3,-20.6,109.1,58), null);


(lib.animate = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.isSingleFrame = false;
	// timeline functions:
	this.frame_0 = function() {
		if(this.isSingleFrame) {
			return;
		}
		if(this.totalFrames == 1) {
			this.isSingleFrame = true;
		}
		var root = this;
		
		var tl = gsap.timeline({repeat:-1});
		
		tl
			.to(root.bg_pic, 18, {scaleX:"1.3", scaleY:"1.3", ease:"none"}, "0")
			.to(root.bg_blue1, 0.3, {alpha:0.0, ease:"Power1.easeOut"}, "0")
			.from(root.tx2, 0.1, {alpha:0.0, ease:"Power1.easeOut"}, "0")
			.from(root.shad2, 0.1, {alpha:0.0, ease:"Power1.easeOut"}, "0.1")
			.from(root.logo, 0.1, {alpha:0.0, ease:"Power1.easeOut"}, "0")
			.from(root.ligal, 0.1, {alpha:0.0, ease:"Power1.easeOut"}, "0")
			.from(root.tx1, 1.5, {x:"+=500", ease:"Power3.easeOut"}, "0.3")
			.from(root.tx1.tx1_1, 1.0, {y:"+=50", alpha:0.0, ease:"Power1.easeOut"}, "2.5")
			.from(root.shad1, 1.7, {alpha:0.0, ease:"Power1.easeOut"}, "0.3")
			.from(root.tx1.tx1_3.s2, 1.0, {y:"-=50", alpha:0.0, ease:"Power1.easeOut"}, "1.5")
			.from(root.tx1.tx1_3.s1, 1.0, {y:"-=50", alpha:0.0, ease:"Power1.easeOut"}, "1.7")
		
		
			
			.to(root.logo.bg_blue, 1.2, {scaleX:"1.8", scaleY:"1.8", y:"-=14", ease:"Power3.easeOut"}, "12")
			.to(root.logo.logo, 1.2, {scaleX:"2.5", scaleY:"2.5", x: "-=310", y: "-=107", ease:"Power3.easeOut"}, "12")
			.from(root.bg_blue2, 0.3, {alpha:0.0, ease:"Power1.easeOut"}, "17.7")
		
		
		;
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// bg_blue1___копия___копия___копия (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EhMPAWHMAAAgsNMCYfAAAMAAAAsNg");
	mask.setTransform(485.3065,124.9966);

	// logo
	this.logo = new lib.logo();
	this.logo.name = "logo";
	this.logo.setTransform(741,211.4,0.8621,0.8619);

	var maskedShapeInstanceList = [this.logo];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.logo).wait(1));

	// Слой_9 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("EghrAMlIAA5JMBDXAAAIAAZJg");
	mask_1.setTransform(490.825,128.25);

	// tx1
	this.tx1 = new lib.tx1();
	this.tx1.name = "tx1";
	this.tx1.setTransform(485.15,128.85,0.7705,0.77,0,0,0,252.8,86.3);

	var maskedShapeInstanceList = [this.tx1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.tx1).wait(1));

	// bg_blue1___копия___копия (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("EhLxATiMAAAgnDMCXjAAAMAAAAnDg");
	mask_2.setTransform(485.0092,124.9966);

	// bg_blue1___копия
	this.bg_blue2 = new lib.bg_blue();
	this.bg_blue2.name = "bg_blue2";
	this.bg_blue2.setTransform(485,125,1,1,0,0,0,485,125);

	var maskedShapeInstanceList = [this.bg_blue2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.bg_blue2).wait(1));

	// bg_blue1
	this.bg_blue1 = new lib.bg_blue();
	this.bg_blue1.name = "bg_blue1";
	this.bg_blue1.setTransform(485,125,1,1,0,0,0,485,125);

	var maskedShapeInstanceList = [this.bg_blue1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.bg_blue1).wait(1));

	// tx2
	this.tx2 = new lib.tx2();
	this.tx2.name = "tx2";
	this.tx2.setTransform(198.9,37.1,1,0.9998,0,0,0,52.6,20.9);

	var maskedShapeInstanceList = [this.tx2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.tx2).wait(1));

	// shad1
	this.shad2 = new lib.shad1();
	this.shad2.name = "shad2";
	this.shad2.setTransform(384,71.1,0.6214,0.3243,0,0,0,314.1,106.4);

	var maskedShapeInstanceList = [this.shad2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.shad2).wait(1));

	// ligal
	this.ligal = new lib.ligal();
	this.ligal.name = "ligal";
	this.ligal.setTransform(348.6,236.55,0.8896,0.8891,0,0,0,222.2,8.2);
	this.ligal.alpha = 0.9219;

	var maskedShapeInstanceList = [this.ligal];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.ligal).wait(1));

	// shad1
	this.shad1 = new lib.shad1();
	this.shad1.name = "shad1";
	this.shad1.setTransform(215.2,260.4,1.3181,0.3243);
	this.shad1.compositeOperation = "multiply";

	this.shad1_1 = new lib.shad1();
	this.shad1_1.name = "shad1_1";
	this.shad1_1.setTransform(422,97.8,1.3181,0.3243);
	this.shad1_1.compositeOperation = "multiply";

	var maskedShapeInstanceList = [this.shad1,this.shad1_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shad1_1},{t:this.shad1}]}).wait(1));

	// terra_bg_970_jpg
	this.bg_pic = new lib.bg_pic();
	this.bg_pic.name = "bg_pic";
	this.bg_pic.setTransform(485.15,125.5,0.7686,0.7692,0,0,0,0.2,0.1);

	var maskedShapeInstanceList = [this.bg_pic];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.bg_pic).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.animate, new cjs.Rectangle(0,0,970,250), null);


// stage content:
(lib.terra_960x250elastic = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	this.isSingleFrame = false;
	// timeline functions:
	this.frame_0 = function() {
		if(this.isSingleFrame) {
			return;
		}
		if(this.totalFrames == 1) {
			this.isSingleFrame = true;
		}
		this.stop()
		 
		var page_body = document.getElementsByTagName("body")[0];
		page_body.style.overflow = "hidden";
		page_body.style.position = "fixed";
		var page_canvas = document.getElementsByTagName("canvas")[0]
		 
		var _this = this
		
			function onResize() {
				var newWidth = window.innerWidth; 
		
				var _widht = stage.scaleX
				if (_widht == 1) {
					var delta = newWidth / page_canvas.width + 0.01
				} else {
					var delta = (newWidth / page_canvas.width + 0.01) * 2
				}
				_this.rr.x = newWidth;
				_this.main.x = newWidth / 2;
				_this.shad_m.x = newWidth / 2;
			
				_this.main.logo.x = main / 2;
		
		
			};
		
		window.onresize = function () {
			onResize();
		}
		
		onResize();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// bord
	this.ll = new lib.rr();
	this.ll.name = "ll";
	this.ll.setTransform(0,0.5);

	this.rr = new lib.rr();
	this.rr.name = "rr";
	this.rr.setTransform(3000,0.5);

	this.line_btm = new lib.l();
	this.line_btm.name = "line_btm";
	this.line_btm.setTransform(1250,249.5);

	this.line_top = new lib.l();
	this.line_top.name = "line_top";
	this.line_top.setTransform(1250,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.line_top},{t:this.line_btm},{t:this.rr},{t:this.ll}]}).wait(1));

	// main
	this.main = new lib.animate();
	this.main.name = "main";
	this.main.setTransform(1477.6,113.3,1,1,0,0,0,462.6,113.3);

	this.timeline.addTween(cjs.Tween.get(this.main).wait(1));

	// shad
	this.shad_m = new lib.shad1();
	this.shad_m.name = "shad_m";
	this.shad_m.setTransform(1500.7,125.3,3.4043,2.5162,0,0,0,0.2,0.3);

	this.timeline.addTween(cjs.Tween.get(this.shad_m).wait(1));

	// Слой_3
	this.bg_main = new lib.bg_main();
	this.bg_main.name = "bg_main";
	this.bg_main.setTransform(1499.95,124.9,1.2012,1.001,0,0,0,1248.7,125.9);

	this.timeline.addTween(cjs.Tween.get(this.bg_main).wait(1));

	// stageBackground
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("rgba(0,0,0,0)").ss(1,1,1,3,true).p("Ejr7gVFMHX3AAAMAAAAqLMnX3AAAg");
	this.shape.setTransform(1500,125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ejr7AVGMAAAgqLMHX3AAAMAAAAqLg");
	this.shape_1.setTransform(1500,125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(1250,-215.9,1751,806);
// library properties:
lib.properties = {
	id: 'AC5308E581C9DC4DB5D44204AB0025B1',
	width: 3000,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"index_atlas_1.jpg", id:"index_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['AC5308E581C9DC4DB5D44204AB0025B1'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;